In [88]:
import pandas as pd
import numpy as np

Q1. Pandas version

In [89]:
# Q1. What version of Pandas did you install?

pd.__version__

'3.0.6'

In [90]:
import os
print(os.getcwd())

c:\Users\dell\Desktop\Data-Development\ml-zoomcamp-course\homework

In [91]:
df = pd.read_csv('car_fuel_efficiency_2026.csv')

In [92]:
df.head(5)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

Q2. Records count

In [93]:
# How many records are in the dataset?

df.shape[0]

10000

Q3. Fuel types

In [94]:
# How many fuel types are presented in the dataset?

len(df['fuel_type'].unique())

3

In [95]:
# To know how many cars for each fuel type

df.fuel_type.value_counts()

fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64

Q4. Missing values

In [117]:
# How many columns in the dataset have missing values?

(df.isnull().sum() > 0).sum()

np.int64(2)

Q5. Max fuel efficiency

In [97]:
# What's the maximum fuel efficiency of cars from Asia?

df['fuel_efficiency_mpg'].groupby(df['origin']).max()

# Another method:
# df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

origin
Asia      41.2
Europe    39.4
USA       38.2
Name: fuel_efficiency_mpg, dtype: float64

In [118]:
df['fuel_efficiency_mpg'][df['origin'] == 'Asia'].max()

np.float64(41.2)

Q6. Median value of horsepower

Find the median value of the horsepower column in the dataset.
Next, calculate the most frequent value of the same horsepower column.
Use the fillna method to fill the missing values in the horsepower column with the most frequent value from the previous step.
Now, calculate the median value of horsepower once again.
Has it changed?

Yes, it increased
Yes, it decreased
No

In [120]:
before = df['horsepower'].median()
before

np.float64(254.0)

In [99]:
df['horsepower'].mode()

0    252.0
Name: horsepower, dtype: float64

In [123]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode()[0])
df['horsepower']

0       243.0
1       272.0
2       267.0
3       258.0
4       304.0
        ...
9995    271.0
9996    244.0
9997    267.0
9998    270.0
9999    295.0
Name: horsepower, Length: 10000, dtype: float64

In [101]:
df.sample(5)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
5899,2019,Europe,Gasoline,All-wheel drive,3,2420,6,223.0,4390,22.2,32.3
7260,1990,USA,Gasoline,Front-wheel drive,4,2470,6,279.0,4530,17.1,27.3
9916,1990,Asia,Gasoline,Front-wheel drive,2,2170,6,213.0,4120,19.3,28.2
8782,1995,Europe,Gasoline,Front-wheel drive,4,2200,6,204.0,3870,NaN,30.9
5386,2002,USA,Gasoline,Front-wheel drive,2,2090,5,218.0,3810,16.8,32.3

In [124]:
# Median value again

after = df['horsepower'].median()
after

np.float64(252.0)

Q7. Sum of weights

Select all the cars from Asia
Select only columns vehicle_weight and model_year
Select the first 7 values
Get the underlying NumPy array. Let's call it X.
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
Invert XTX.
Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
What's the sum of all the elements of the result?
Note: You just implemented linear regression. We'll talk about it in the next lesson.

In [103]:
df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7)

#df[['vehicle_weight', 'model_year']].groupby(df['origin'] == 'Asia')

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [104]:
# Get the underlying NumPy array. Let's call it X.

X = np.array(df[df['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(7))
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [105]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

XTX = X.T @ X       # Or, XTX = X.T.dot(X)
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [106]:
# Invert XTX.

XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [107]:

check = XTX_inv.dot(XTX)    # Or, check = np.dot(XTX_inv, XTX), Or, check = XTX_inv @ XTX
check

array([[ 1.00000000e+00, -7.77917769e-15],
       [-8.75935812e-14,  1.00000000e+00]])

In [108]:
# Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200]

y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [109]:
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w

w = XTX_inv.dot(X.T).dot(y)    # Or, w = np.dot(XTX_inv, X.T.dot(y)), Or, w = XTX_inv @ X.T @ y
w

array([0.13644777, 0.2327492 ])

In [111]:
# Sum

w_sum = np.sum(w).round(2)
w_sum

np.float64(0.37)